### ISSUE TITLE
Incorrect path to script & dataset

### ISSUE THREAD

**Issue by pbavinck** [GoogleCloudPlatform/serverless-spark-workshop#3]
Step 7. fails as the path to the scripts and datasets is incorrect
```shell
cd ~/serverless-spark-workshop/lab-01/
gsutil cp -r cell-tower-anomaly-detection/00-scripts gs://$CODE_AND_DATA_BUCKET/cell-tower-anomaly-detection/00-scripts
gsutil cp -r cell-tower-anomaly-detection/01-datasets gs://$CODE_AND_DATA_BUCKET/cell-tower-anomaly-detection/01-datasets
```

The paths in the repo seem to be:
- cell-tower-anomaly-detection/cell-tower-anomaly-detection/00-scripts
- cell-tower-anomaly-detection/cell-tower-anomaly-detection/01-datasets

**Comment by kmting** [comment]
Fixed.  Thanks @pbavinck for the catch.
