### ISSUE TITLE
Error: Invalid reference

### ISSUE THREAD

**Issue by phwelo** [GoogleCloudPlatform/serverless-spark-workshop#36]
│ Error: Invalid reference
│ 
│   on .terraform/modules/serverless-spark-workshop/s8s-prerequisites/00-scripts-and-config/terraform/main.tf line 866, in output "CUSTOM_CONTAINER_IMAGE_PATH":
│  866: value = "${local.location}-docker.pkg.dev/${local.project_id}/${local.s8s_artifact_repository_nm}/s8s-spark-image:${spark_container_img_tag}"
│ 
│ A reference to a resource type must be followed by at least one attribute
│ access, specifying the resource name.

You already have a PR with the fix: [https://github.com/GoogleCloudPlatform/serverless-spark-workshop/pull/35](https://github.com/GoogleCloudPlatform/serverless-spark-workshop/pull/35)

**Comment by kmting** [comment]
Thanks for reporting this.  The fix has been committed.
