### ISSUE TITLE
No definition of the Prerequisite

### ISSUE THREAD

**Issue by pbavinck** [GoogleCloudPlatform/serverless-spark-workshop#4]
The 1. Prerequites only says:
```
Successful environment creation
```

This is not very helpful. It would be nice if (at least) the Prerequites states all the resources that need to be in place. Even better would be to include the `gcloud` commend to create the necessary resources.

**Comment by kmting** [comment]
Agreed.  Lab 1 now points to the refactored version by @velascoluis which includes Terraform scripts that take care of the prereqs: https://github.com/GoogleCloudPlatform/serverless-spark-workshop/blob/main/cell-tower-anomaly-detection-dbt/README.md  

The other labs do include the prereqs.
