### ISSUE TITLE
Illegal VPC name

### ISSUE THREAD

**Issue by pbavinck** [GoogleCloudPlatform/serverless-spark-workshop#5]
The list of environment variables contains the following:
```
VPC_NM=VPC=s8s-vpc-$PROJECT_NBR
```

After project number substitution this results in an illegal VPC name for variable `VPC_NM` ("VPC=s8s-vpc-XXXXXXXXXX" in Cloud shell).

Perhaps what is meant here is:
```
VPC_NM=s8s-vpc-$PROJECT_NBR
VPC=s8s-vpc-$PROJECT_NBR
```

**Comment by kmting** [comment]
Fixed.  Thanks for the catch.
